name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
env:
  APP_NAME: devopsshack-java-demo
    
jobs:
  pre_build:
    name: compile project

    runs-on: self-hosted
    env:
      STAGE_NAME: BEFORE-PACKAGE
      
      

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  | 
        mvn compile
        mvn test
        echo "App Name: $APP_NAME"
        echo "stage-name: $STAGE_NAME"

        
  build:
    
    name: build

    runs-on: self-hosted
    needs: pre_build

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  | 
        mvn package
        echo "App Name: $APP_NAME"
        echo "stage-name: $STAGE_NAME"
        
      
 
